name: Download Echo APK and Create Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download ed estrai
        run: |
          curl -L -o echo-artifact.zip https://nightly.link/brahmkshatriya/echo/workflows/nightly/main/artifact.zip
          unzip -q echo-artifact.zip
          APK=$(find . -name "*.apk" -type f | head -n 1)
          
          # Formato: 11-02-2026_18-30
          DATE=$(date +%d-%m-%Y_%H-%M)
          echo "RELEASE_TAG=$DATE" >> $GITHUB_ENV
          
          cp "$APK" "echo-${DATE}.apk"
          cp "$APK" echo-latest.apk

#      - name: Upload APK as Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: echo-apk-${{ env.RELEASE_TAG }}
#          path: echo-*.apk
#          retention-days: 7 # Opzionale: elimina l'artifact dopo 7 giorni per risparmiare spazio
          

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Echo ${{ env.RELEASE_TAG }}
          body: |
            ### ðŸ“¦ Echo Nightly Build
            - **Data caricamento:** ${{ env.RELEASE_TAG }}
            - **Sorgente:** [Nightly Link](https://nightly.link/brahmkshatriya/echo/workflows/nightly/main/artifact.zip)

            *This repository is not affiliated with Echo*
            L'APK `echo-latest.apk` punta sempre all'ultima versione caricata in questa release.
          draft: false
          prerelease: false
          files: |
            echo-${{ env.RELEASE_TAG }}.apk
            echo-latest.apk
